language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install:
  - python setup.py sdist
  - pip install dist/sphinxcontrib.divparams-*.tar.gz

script:
  - cd test
  - ./runtest.sh

before_install:
  - pip install sphinx
  - pip install beautifulsoup4
  - pip install codecov

after_success:
  - codecov
